### ISSUE TITLE
B2 Feedback

### ISSUE THREAD

**Issue by yuliaUU** [stat545ubc-2021/ballinstat545b2#1]
Great work

- I was able to load the library and run the example
- but ? did not work:
![image](https://user-images.githubusercontent.com/54612866/143798176-6bb2b7ff-0198-4c35-87b4-6d720b4182d7.png)
- did not pass check() 
![image](https://user-images.githubusercontent.com/54612866/143798568-5b446bb5-977b-4d43-a90a-3eb45d9a12d0.png)
- test() passed
- tesstthat has extra code `datateachr::steam_games %>%   count(is.na(languages))`  unrelated to tests

**Comment by mxballin** [comment]
Hmm. Weird! It worked on my machine when I tried loading it in to a new project space, but maybe it was still drawing from the local documents.

Thanks, Yulia!

**Comment by yuliaUU** [comment]
actually the ? wworks, but somehow outputs all these warnings;/ have no idea why
